/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    media: Media;
    subsidiaries: Subsidiary;
    'company-values': CompanyValue;
    news: News;
    pages: Page;
    testimonials: Testimonial;
    faqs: Faq;
    certifications: Certification;
    services: Service;
    'contact-submissions': ContactSubmission;
    'dossier-documents': DossierDocument;
    'dossier-submissions': DossierSubmission;
    'job-openings': JobOpening;
    'job-applications': JobApplication;
    'payload-kv': PayloadKv;
    users: User;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    media: MediaSelect<false> | MediaSelect<true>;
    subsidiaries: SubsidiariesSelect<false> | SubsidiariesSelect<true>;
    'company-values': CompanyValuesSelect<false> | CompanyValuesSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    certifications: CertificationsSelect<false> | CertificationsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    'dossier-documents': DossierDocumentsSelect<false> | DossierDocumentsSelect<true>;
    'dossier-submissions': DossierSubmissionsSelect<false> | DossierSubmissionsSelect<true>;
    'job-openings': JobOpeningsSelect<false> | JobOpeningsSelect<true>;
    'job-applications': JobApplicationsSelect<false> | JobApplicationsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'fr' | 'it') | ('en' | 'fr' | 'it')[];
  globals: {
    header: Header;
    footer: Footer;
    'contact-info': ContactInfo;
    'home-page-content': HomePageContent;
    'about-page-content': AboutPageContent;
    'notre-modele-content': NotreModeleContent;
    'participations-page-content': ParticipationsPageContent;
    'actualites-page-content': ActualitesPageContent;
    'impact-page-content': ImpactPageContent;
    'carrieres-page-content': CarrieresPageContent;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'contact-info': ContactInfoSelect<false> | ContactInfoSelect<true>;
    'home-page-content': HomePageContentSelect<false> | HomePageContentSelect<true>;
    'about-page-content': AboutPageContentSelect<false> | AboutPageContentSelect<true>;
    'notre-modele-content': NotreModeleContentSelect<false> | NotreModeleContentSelect<true>;
    'participations-page-content': ParticipationsPageContentSelect<false> | ParticipationsPageContentSelect<true>;
    'actualites-page-content': ActualitesPageContentSelect<false> | ActualitesPageContentSelect<true>;
    'impact-page-content': ImpactPageContentSelect<false> | ImpactPageContentSelect<true>;
    'carrieres-page-content': CarrieresPageContentSelect<false> | CarrieresPageContentSelect<true>;
  };
  locale: 'en' | 'fr' | 'it';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subsidiaries".
 */
export interface Subsidiary {
  id: number;
  name: string;
  slug?: string | null;
  category:
    | 'Solutions Digitales'
    | 'Restauration'
    | 'Architecture & Design'
    | 'Géotechnique & Génie Civil'
    | 'Loisirs & Bien-Être'
    | 'Gestion Fourrière';
  logo?: (number | null) | Media;
  featuredImage?: (number | null) | Media;
  shortDescription?: string | null;
  fullDescription?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  websiteUrl?: string | null;
  featuredInHome?: boolean | null;
  order?: number | null;
  participationLabel?: string | null;
  entryYear?: number | null;
  accentColor?: ('teal' | 'red' | 'orange' | 'gray') | null;
  detailUrl?: string | null;
  stats?:
    | {
        label?: string | null;
        value?: string | null;
        id?: string | null;
      }[]
    | null;
  city?: string | null;
  country?: string | null;
  companyOverviewIntro?: string | null;
  legalName?: string | null;
  activityLabel?: string | null;
  headcount?: string | null;
  foundedYear?: number | null;
  certificationLabel?: string | null;
  motivationPoints?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  entrySituationPoints?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  polesActive?:
    | (
        | 'Growth, Marketing & Brand'
        | 'Développement informatique'
        | 'Comptabilité & Fiscalité'
        | 'Procurement'
        | 'Ressources Humaines'
      )[]
    | null;
  startingSituationBody?: string | null;
  whatKrestDidBody?: string | null;
  resultBody?: string | null;
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  governanceIntro?: string | null;
  participationType?: string | null;
  boardRepresentation?: string | null;
  reportingFrequency?: string | null;
  engagementDuration?: string | null;
  operationalDirection?: string | null;
  participationStatus?: string | null;
  synergiesIntro?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "company-values".
 */
export interface CompanyValue {
  id: number;
  title: string;
  description?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  title: string;
  slug: string;
  excerpt?: string | null;
  featuredImage?: (number | null) | Media;
  category?: string | null;
  author?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  publishedAt?: string | null;
  relatedSubsidiaries?: (number | Subsidiary)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  authorName: string;
  authorTitle?: string | null;
  avatar?: (number | null) | Media;
  quote: string;
  companyLogo?: (number | null) | Media;
  rating?: number | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  category?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certifications".
 */
export interface Certification {
  id: number;
  title: string;
  code: string;
  description?: string | null;
  badgeIcon?: (number | null) | Media;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  slug?: string | null;
  description?: string | null;
  example?: string | null;
  icon?: (number | null) | Media;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  headerImage?: (number | null) | Media;
  videoUrl?: string | null;
  featuredInHero?: boolean | null;
  order?: number | null;
  preview?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: number;
  fullName: string;
  motif: 'parcours-prioritaire' | 'investisseur-partenaire' | 'presse' | 'candidat' | 'autre';
  email: string;
  phoneCountryCode?: string | null;
  phoneNumber: string;
  organization: string;
  country: string;
  projectDescription: string;
  consentAccepted: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dossier-documents".
 */
export interface DossierDocument {
  id: number;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dossier-submissions".
 */
export interface DossierSubmission {
  id: number;
  reference?: string | null;
  companyName: string;
  industry: string;
  foundedYear: number;
  headcount: string;
  cityCountry: string;
  websiteUrl?: string | null;
  needType?: ('Capital' | 'Structuration' | 'Accès au marché' | 'Autre') | null;
  amountRange?: ('lt-10m' | '10m-50m' | '50m-200m' | 'gt-200m' | 'non-determine') | null;
  projectDescription: string;
  documents?: (number | DossierDocument)[] | null;
  consentAccepted: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-openings".
 */
export interface JobOpening {
  id: number;
  title: string;
  relatedSubsidiary?: (number | null) | Subsidiary;
  contractType?: ('CDI' | 'CDD' | 'Stage' | 'Freelance') | null;
  location?: string | null;
  description?: string | null;
  publishedAt?: string | null;
  applicationDeadline?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-applications".
 */
export interface JobApplication {
  id: number;
  fullName: string;
  phone: string;
  email: string;
  targetEntityOrSector: string;
  desiredRole: string;
  targetCity: string;
  documents?: (number | DossierDocument)[] | null;
  consentAccepted: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'subsidiaries';
        value: number | Subsidiary;
      } | null)
    | ({
        relationTo: 'company-values';
        value: number | CompanyValue;
      } | null)
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'certifications';
        value: number | Certification;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: number | ContactSubmission;
      } | null)
    | ({
        relationTo: 'dossier-documents';
        value: number | DossierDocument;
      } | null)
    | ({
        relationTo: 'dossier-submissions';
        value: number | DossierSubmission;
      } | null)
    | ({
        relationTo: 'job-openings';
        value: number | JobOpening;
      } | null)
    | ({
        relationTo: 'job-applications';
        value: number | JobApplication;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subsidiaries_select".
 */
export interface SubsidiariesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  category?: T;
  logo?: T;
  featuredImage?: T;
  shortDescription?: T;
  fullDescription?: T;
  websiteUrl?: T;
  featuredInHome?: T;
  order?: T;
  participationLabel?: T;
  entryYear?: T;
  accentColor?: T;
  detailUrl?: T;
  stats?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  city?: T;
  country?: T;
  companyOverviewIntro?: T;
  legalName?: T;
  activityLabel?: T;
  headcount?: T;
  foundedYear?: T;
  certificationLabel?: T;
  motivationPoints?:
    | T
    | {
        text?: T;
        id?: T;
      };
  entrySituationPoints?:
    | T
    | {
        text?: T;
        id?: T;
      };
  polesActive?: T;
  startingSituationBody?: T;
  whatKrestDidBody?: T;
  resultBody?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  governanceIntro?: T;
  participationType?: T;
  boardRepresentation?: T;
  reportingFrequency?: T;
  engagementDuration?: T;
  operationalDirection?: T;
  participationStatus?: T;
  synergiesIntro?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "company-values_select".
 */
export interface CompanyValuesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  featuredImage?: T;
  category?: T;
  author?: T;
  content?: T;
  publishedAt?: T;
  relatedSubsidiaries?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  content?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  authorName?: T;
  authorTitle?: T;
  avatar?: T;
  quote?: T;
  companyLogo?: T;
  rating?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certifications_select".
 */
export interface CertificationsSelect<T extends boolean = true> {
  title?: T;
  code?: T;
  description?: T;
  badgeIcon?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  example?: T;
  icon?: T;
  content?: T;
  headerImage?: T;
  videoUrl?: T;
  featuredInHero?: T;
  order?: T;
  preview?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  fullName?: T;
  motif?: T;
  email?: T;
  phoneCountryCode?: T;
  phoneNumber?: T;
  organization?: T;
  country?: T;
  projectDescription?: T;
  consentAccepted?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dossier-documents_select".
 */
export interface DossierDocumentsSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dossier-submissions_select".
 */
export interface DossierSubmissionsSelect<T extends boolean = true> {
  reference?: T;
  companyName?: T;
  industry?: T;
  foundedYear?: T;
  headcount?: T;
  cityCountry?: T;
  websiteUrl?: T;
  needType?: T;
  amountRange?: T;
  projectDescription?: T;
  documents?: T;
  consentAccepted?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-openings_select".
 */
export interface JobOpeningsSelect<T extends boolean = true> {
  title?: T;
  relatedSubsidiary?: T;
  contractType?: T;
  location?: T;
  description?: T;
  publishedAt?: T;
  applicationDeadline?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-applications_select".
 */
export interface JobApplicationsSelect<T extends boolean = true> {
  fullName?: T;
  phone?: T;
  email?: T;
  targetEntityOrSector?: T;
  desiredRole?: T;
  targetCity?: T;
  documents?: T;
  consentAccepted?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  logo?: (number | null) | Media;
  navItems?:
    | {
        label: string;
        url: string;
        subItems?:
          | {
              label: string;
              url: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  ctaLabel?: string | null;
  ctaUrl?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  columns?:
    | {
        columnTitle: string;
        links?:
          | {
              label: string;
              url: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  participationsColumnTitle?: string | null;
  socialLinks?:
    | {
        platform: string;
        url: string;
        icon?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  copyrightNotice?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-info".
 */
export interface ContactInfo {
  id: number;
  emails?:
    | {
        email: string;
        id?: string | null;
      }[]
    | null;
  phones?:
    | {
        phone: string;
        id?: string | null;
      }[]
    | null;
  physicalAddress?: string | null;
  postalBox?: string | null;
  mapIframeUrl?: string | null;
  legalName?: string | null;
  linkedinUrl?: string | null;
  twitterUrl?: string | null;
  openingHours?: string | null;
  directionsUrl?: string | null;
  rccmNumber?: string | null;
  taxpayerNumber?: string | null;
  legalNoticeUrl?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page-content".
 */
export interface HomePageContent {
  id: number;
  heroHeading?: string | null;
  heroSubheading?: string | null;
  heroCtaLabel?: string | null;
  heroCtaUrl?: string | null;
  heroSecondaryCtaLabel?: string | null;
  heroSecondaryCtaUrl?: string | null;
  heroBgMedia?: (number | null) | Media;
  aboutKicker?: string | null;
  aboutIntroHeading?: string | null;
  aboutIntroBody?: string | null;
  aboutQuoteAvatar?: (number | null) | Media;
  aboutQuoteAuthorName?: string | null;
  aboutQuoteAuthorTitle?: string | null;
  aboutQuoteText?: string | null;
  aboutTags?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  aboutSecondKicker?: string | null;
  aboutStatsHeading?: string | null;
  aboutStatsBody?: string | null;
  aboutStats?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  aboutCtaLabel?: string | null;
  aboutCtaUrl?: string | null;
  polesKicker?: string | null;
  polesHeading?: string | null;
  modelKicker?: string | null;
  modelHeading?: string | null;
  modelBody?: string | null;
  modelSteps?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  processHeading?: string | null;
  processSteps?:
    | {
        title: string;
        duration: string;
        id?: string | null;
      }[]
    | null;
  processNoteTitle?: string | null;
  processNoteBody?: string | null;
  processCtaLabel?: string | null;
  processCtaUrl?: string | null;
  subsidiariesKicker?: string | null;
  subsidiariesHeading?: string | null;
  subsidiariesSubheading?: string | null;
  synergiesHeading?: string | null;
  synergies?:
    | {
        entityA: number | Subsidiary;
        entityB: number | Subsidiary;
        description: string;
        id?: string | null;
      }[]
    | null;
  faqImage?: (number | null) | Media;
  certificationsKicker?: string | null;
  certificationsHeading?: string | null;
  certificationsBody?: string | null;
  testimonialsKicker?: string | null;
  testimonialsHeading?: string | null;
  testimonialsCtaLabel?: string | null;
  testimonialsCtaUrl?: string | null;
  newsKicker?: string | null;
  newsHeading?: string | null;
  contactKicker?: string | null;
  contactHeading?: string | null;
  contactConfidentialityTitle?: string | null;
  contactConfidentialityBody?: string | null;
  contactChecklist?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  contactEmail?: string | null;
  contactAddress?: string | null;
  newsletterKicker?: string | null;
  newsletterHeading?: string | null;
  newsletterPlaceholder?: string | null;
  newsletterButtonLabel?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page-content".
 */
export interface AboutPageContent {
  id: number;
  pageTitle?: string | null;
  historyTitle?: string | null;
  historyBody?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  historyImage?: (number | null) | Media;
  perspectivesTitle?: string | null;
  perspectivesBody?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  perspectivesImage?: (number | null) | Media;
  visionTitle?: string | null;
  visionBody?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  missionTitle?: string | null;
  missionBody?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notre-modele-content".
 */
export interface NotreModeleContent {
  id: number;
  heroHeading?: string | null;
  thesisKicker?: string | null;
  thesisIntro?: string | null;
  thesisBody?: string | null;
  thesisQuote?: string | null;
  sectorsKicker?: string | null;
  sectorsIntro?: string | null;
  sectorCards?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  interventionZones?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  interventionZonesImage?: (number | null) | Media;
  polesKicker?: string | null;
  polesHeading?: string | null;
  polesIntro?: string | null;
  poleCards?:
    | {
        title: string;
        examples?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  caseStudyKicker?: string | null;
  caseStudyHeading?: string | null;
  caseStudyIntro?: string | null;
  caseStudySituationTitle?: string | null;
  caseStudySituationBody?: string | null;
  caseStudyActionTitle?: string | null;
  caseStudyActionBody?: string | null;
  caseStudyResultTitle?: string | null;
  caseStudyResultBody?: string | null;
  caseStudyCtaTitle?: string | null;
  caseStudyCtaBody?: string | null;
  caseStudyCtaPrimaryLabel?: string | null;
  caseStudyCtaPrimaryUrl?: string | null;
  caseStudyCtaSecondaryLabel?: string | null;
  caseStudyCtaSecondaryUrl?: string | null;
  impactKicker?: string | null;
  impactHeading?: string | null;
  impactStats?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  impactCtaLabel?: string | null;
  impactCtaUrl?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "participations-page-content".
 */
export interface ParticipationsPageContent {
  id: number;
  heroHeading?: string | null;
  heroSubheading?: string | null;
  heroStats?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  portfolioKicker?: string | null;
  portfolioHeading?: string | null;
  portfolioSubheading?: string | null;
  synergiesKicker?: string | null;
  synergiesHeading?: string | null;
  synergiesSubheading?: string | null;
  synergies?:
    | {
        entityA: number | Subsidiary;
        entityB: number | Subsidiary;
        description: string;
        id?: string | null;
      }[]
    | null;
  compositionKicker?: string | null;
  compositionSubheading?: string | null;
  sectorBreakdown?:
    | {
        label: string;
        percentage: number;
        id?: string | null;
      }[]
    | null;
  ownershipBreakdown?:
    | {
        rank: string;
        rankColor?: ('orange' | 'teal') | null;
        label: string;
        percentage: number;
        barColor?: ('orange' | 'gray') | null;
        id?: string | null;
      }[]
    | null;
  timelineKicker?: string | null;
  timelineSubheading?: string | null;
  foundingYear?: number | null;
  foundingLabel?: string | null;
  ctaLeftHeading?: string | null;
  ctaLeftBody?: string | null;
  ctaLeftPrimaryLabel?: string | null;
  ctaLeftPrimaryUrl?: string | null;
  ctaLeftSecondaryLabel?: string | null;
  ctaLeftSecondaryUrl?: string | null;
  ctaRightHeading?: string | null;
  ctaRightBody?: string | null;
  ctaRightPrimaryLabel?: string | null;
  ctaRightPrimaryUrl?: string | null;
  ctaRightSecondaryLabel?: string | null;
  ctaRightSecondaryUrl?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "actualites-page-content".
 */
export interface ActualitesPageContent {
  id: number;
  portfolioKicker?: string | null;
  pressHeading?: string | null;
  pressLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  pressCtaLabel?: string | null;
  pressCtaUrl?: string | null;
  newsletterInfoLines?:
    | {
        label: string;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  newsletterFormLabel?: string | null;
  newsletterPlaceholder?: string | null;
  newsletterButtonLabel?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "impact-page-content".
 */
export interface ImpactPageContent {
  id: number;
  heroHeading?: string | null;
  heroSubheading?: string | null;
  statsKicker?: string | null;
  statsHeading?: string | null;
  statsIntro?: string | null;
  stats?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  jobsKicker?: string | null;
  jobsChartHeading?: string | null;
  jobsChartData?:
    | {
        label: string;
        value: number;
        id?: string | null;
      }[]
    | null;
  jobsInfoCards?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  storyKicker?: string | null;
  storyHeading?: string | null;
  storyIntro?: string | null;
  storySituationTitle?: string | null;
  storySituationBody?: string | null;
  storyActionTitle?: string | null;
  storyActionBody?: string | null;
  storyResultTitle?: string | null;
  storyResultBody?: string | null;
  storyCtaTitle?: string | null;
  storyCtaBody?: string | null;
  storyCtaPrimaryLabel?: string | null;
  storyCtaPrimaryUrl?: string | null;
  storyCtaSecondaryLabel?: string | null;
  storyCtaSecondaryUrl?: string | null;
  esgKicker?: string | null;
  esgHeading?: string | null;
  esgCert1Title?: string | null;
  esgCert1Scope?: string | null;
  esgCert2Title?: string | null;
  esgCert2Scope?: string | null;
  esgEngagementTitle?: string | null;
  esgEngagementItems?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carrieres-page-content".
 */
export interface CarrieresPageContent {
  id: number;
  heroHeading?: string | null;
  jobsKicker?: string | null;
  jobsChartHeading?: string | null;
  jobsChartData?:
    | {
        label: string;
        value: number;
        id?: string | null;
      }[]
    | null;
  jobsSkillTags?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  jobsLocationTags?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  whyKicker?: string | null;
  whyHeading?: string | null;
  whyCards?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  offersKicker?: string | null;
  offersIntro?: string | null;
  offersHeading?: string | null;
  processKicker?: string | null;
  processIntro?: string | null;
  processHeading?: string | null;
  processSteps?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  spontaneousKicker?: string | null;
  spontaneousHeadingLine1?: string | null;
  spontaneousHeadingLine2?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  logo?: T;
  navItems?:
    | T
    | {
        label?: T;
        url?: T;
        subItems?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  ctaLabel?: T;
  ctaUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  description?: T;
  columns?:
    | T
    | {
        columnTitle?: T;
        links?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  participationsColumnTitle?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        icon?: T;
        id?: T;
      };
  copyrightNotice?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-info_select".
 */
export interface ContactInfoSelect<T extends boolean = true> {
  emails?:
    | T
    | {
        email?: T;
        id?: T;
      };
  phones?:
    | T
    | {
        phone?: T;
        id?: T;
      };
  physicalAddress?: T;
  postalBox?: T;
  mapIframeUrl?: T;
  legalName?: T;
  linkedinUrl?: T;
  twitterUrl?: T;
  openingHours?: T;
  directionsUrl?: T;
  rccmNumber?: T;
  taxpayerNumber?: T;
  legalNoticeUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page-content_select".
 */
export interface HomePageContentSelect<T extends boolean = true> {
  heroHeading?: T;
  heroSubheading?: T;
  heroCtaLabel?: T;
  heroCtaUrl?: T;
  heroSecondaryCtaLabel?: T;
  heroSecondaryCtaUrl?: T;
  heroBgMedia?: T;
  aboutKicker?: T;
  aboutIntroHeading?: T;
  aboutIntroBody?: T;
  aboutQuoteAvatar?: T;
  aboutQuoteAuthorName?: T;
  aboutQuoteAuthorTitle?: T;
  aboutQuoteText?: T;
  aboutTags?:
    | T
    | {
        label?: T;
        id?: T;
      };
  aboutSecondKicker?: T;
  aboutStatsHeading?: T;
  aboutStatsBody?: T;
  aboutStats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  aboutCtaLabel?: T;
  aboutCtaUrl?: T;
  polesKicker?: T;
  polesHeading?: T;
  modelKicker?: T;
  modelHeading?: T;
  modelBody?: T;
  modelSteps?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  processHeading?: T;
  processSteps?:
    | T
    | {
        title?: T;
        duration?: T;
        id?: T;
      };
  processNoteTitle?: T;
  processNoteBody?: T;
  processCtaLabel?: T;
  processCtaUrl?: T;
  subsidiariesKicker?: T;
  subsidiariesHeading?: T;
  subsidiariesSubheading?: T;
  synergiesHeading?: T;
  synergies?:
    | T
    | {
        entityA?: T;
        entityB?: T;
        description?: T;
        id?: T;
      };
  faqImage?: T;
  certificationsKicker?: T;
  certificationsHeading?: T;
  certificationsBody?: T;
  testimonialsKicker?: T;
  testimonialsHeading?: T;
  testimonialsCtaLabel?: T;
  testimonialsCtaUrl?: T;
  newsKicker?: T;
  newsHeading?: T;
  contactKicker?: T;
  contactHeading?: T;
  contactConfidentialityTitle?: T;
  contactConfidentialityBody?: T;
  contactChecklist?:
    | T
    | {
        item?: T;
        id?: T;
      };
  contactEmail?: T;
  contactAddress?: T;
  newsletterKicker?: T;
  newsletterHeading?: T;
  newsletterPlaceholder?: T;
  newsletterButtonLabel?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page-content_select".
 */
export interface AboutPageContentSelect<T extends boolean = true> {
  pageTitle?: T;
  historyTitle?: T;
  historyBody?: T;
  historyImage?: T;
  perspectivesTitle?: T;
  perspectivesBody?: T;
  perspectivesImage?: T;
  visionTitle?: T;
  visionBody?: T;
  missionTitle?: T;
  missionBody?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notre-modele-content_select".
 */
export interface NotreModeleContentSelect<T extends boolean = true> {
  heroHeading?: T;
  thesisKicker?: T;
  thesisIntro?: T;
  thesisBody?: T;
  thesisQuote?: T;
  sectorsKicker?: T;
  sectorsIntro?: T;
  sectorCards?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  interventionZones?:
    | T
    | {
        label?: T;
        id?: T;
      };
  interventionZonesImage?: T;
  polesKicker?: T;
  polesHeading?: T;
  polesIntro?: T;
  poleCards?:
    | T
    | {
        title?: T;
        examples?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  caseStudyKicker?: T;
  caseStudyHeading?: T;
  caseStudyIntro?: T;
  caseStudySituationTitle?: T;
  caseStudySituationBody?: T;
  caseStudyActionTitle?: T;
  caseStudyActionBody?: T;
  caseStudyResultTitle?: T;
  caseStudyResultBody?: T;
  caseStudyCtaTitle?: T;
  caseStudyCtaBody?: T;
  caseStudyCtaPrimaryLabel?: T;
  caseStudyCtaPrimaryUrl?: T;
  caseStudyCtaSecondaryLabel?: T;
  caseStudyCtaSecondaryUrl?: T;
  impactKicker?: T;
  impactHeading?: T;
  impactStats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  impactCtaLabel?: T;
  impactCtaUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "participations-page-content_select".
 */
export interface ParticipationsPageContentSelect<T extends boolean = true> {
  heroHeading?: T;
  heroSubheading?: T;
  heroStats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  portfolioKicker?: T;
  portfolioHeading?: T;
  portfolioSubheading?: T;
  synergiesKicker?: T;
  synergiesHeading?: T;
  synergiesSubheading?: T;
  synergies?:
    | T
    | {
        entityA?: T;
        entityB?: T;
        description?: T;
        id?: T;
      };
  compositionKicker?: T;
  compositionSubheading?: T;
  sectorBreakdown?:
    | T
    | {
        label?: T;
        percentage?: T;
        id?: T;
      };
  ownershipBreakdown?:
    | T
    | {
        rank?: T;
        rankColor?: T;
        label?: T;
        percentage?: T;
        barColor?: T;
        id?: T;
      };
  timelineKicker?: T;
  timelineSubheading?: T;
  foundingYear?: T;
  foundingLabel?: T;
  ctaLeftHeading?: T;
  ctaLeftBody?: T;
  ctaLeftPrimaryLabel?: T;
  ctaLeftPrimaryUrl?: T;
  ctaLeftSecondaryLabel?: T;
  ctaLeftSecondaryUrl?: T;
  ctaRightHeading?: T;
  ctaRightBody?: T;
  ctaRightPrimaryLabel?: T;
  ctaRightPrimaryUrl?: T;
  ctaRightSecondaryLabel?: T;
  ctaRightSecondaryUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "actualites-page-content_select".
 */
export interface ActualitesPageContentSelect<T extends boolean = true> {
  portfolioKicker?: T;
  pressHeading?: T;
  pressLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  pressCtaLabel?: T;
  pressCtaUrl?: T;
  newsletterInfoLines?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  newsletterFormLabel?: T;
  newsletterPlaceholder?: T;
  newsletterButtonLabel?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "impact-page-content_select".
 */
export interface ImpactPageContentSelect<T extends boolean = true> {
  heroHeading?: T;
  heroSubheading?: T;
  statsKicker?: T;
  statsHeading?: T;
  statsIntro?: T;
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  jobsKicker?: T;
  jobsChartHeading?: T;
  jobsChartData?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  jobsInfoCards?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  storyKicker?: T;
  storyHeading?: T;
  storyIntro?: T;
  storySituationTitle?: T;
  storySituationBody?: T;
  storyActionTitle?: T;
  storyActionBody?: T;
  storyResultTitle?: T;
  storyResultBody?: T;
  storyCtaTitle?: T;
  storyCtaBody?: T;
  storyCtaPrimaryLabel?: T;
  storyCtaPrimaryUrl?: T;
  storyCtaSecondaryLabel?: T;
  storyCtaSecondaryUrl?: T;
  esgKicker?: T;
  esgHeading?: T;
  esgCert1Title?: T;
  esgCert1Scope?: T;
  esgCert2Title?: T;
  esgCert2Scope?: T;
  esgEngagementTitle?: T;
  esgEngagementItems?:
    | T
    | {
        text?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carrieres-page-content_select".
 */
export interface CarrieresPageContentSelect<T extends boolean = true> {
  heroHeading?: T;
  jobsKicker?: T;
  jobsChartHeading?: T;
  jobsChartData?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  jobsSkillTags?:
    | T
    | {
        text?: T;
        id?: T;
      };
  jobsLocationTags?:
    | T
    | {
        text?: T;
        id?: T;
      };
  whyKicker?: T;
  whyHeading?: T;
  whyCards?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  offersKicker?: T;
  offersIntro?: T;
  offersHeading?: T;
  processKicker?: T;
  processIntro?: T;
  processHeading?: T;
  processSteps?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  spontaneousKicker?: T;
  spontaneousHeadingLine1?: T;
  spontaneousHeadingLine2?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}